version: "3.9"

services:
  mysql:
    image: mysql:8.0
    container_name: mysql_banbajio
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: banbajio
    volumes:
      - ./bd/init:/docker-entrypoint-initdb.d
    ports:
      - "3307:3306"
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 5s
      retries: 5

  app:
    image: banbajio-app:latest
    container_name: bajio-app
    depends_on:
      mysql:
        condition: service_healthy
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/banbajio?allowPublicKeyRetrieval=true&useSSL=false&serverTimezone=UTC
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root
    ports:
      - "8080:8080"

  frontend:
    build: ./front/FrontBanbajio
    container_name: angular-frontend
    depends_on:
      - app
    ports:
      - "80:80"
